# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 1.047
    has_acceleration_limits: true
    max_acceleration: 1.396
  shoulder_lift_joint:
    max_position: 0.0
    min_position: -3.14
    has_velocity_limits: true
    max_velocity: 1.047
    has_acceleration_limits: true
    max_acceleration: 1.396
  elbow_joint:
    min_position: 0.0
    has_velocity_limits: true
    max_velocity: 1.047
    has_acceleration_limits: true
    max_acceleration: 1.396
  wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 1.047
    has_acceleration_limits: true
    max_acceleration: 1.396
  wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 1.047
    has_acceleration_limits: true
    max_acceleration: 1.396
  wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 1.047
    has_acceleration_limits: true
    max_acceleration: 1.396
